### ISSUE TITLE
Cant run released phx app (distillery)

### ISSUE THREAD

**Issue by maxxst** [marcelotto/sparql-ex#2]
Hey everyone.

I built a simple Phoenix Backend that calls dbpedia via the sparql-client. I'm now trying to get the app ready for deployment. I was trying to use distillery for that. But when I `MIX_ENV=prod mix release` and then run the app in the foreground I get the following error:

```
[info] Application sparql exited: SPARQL.Application.start(:normal, []) returned an error: shutdown: failed to start child: SPARQL.ExtensionFunction.Registry
    ** (EXIT) exited in: GenServer.call(Mix.ProjectStack, {:get, #Function<11.118167275/1 in Mix.ProjectStack.peek/0>}, 30000)
        ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
{"Kernel pid terminated",application_controller,"{application_start_failure,sparql,{{shutdown,{failed_to_start_child,'Elixir.SPARQL.ExtensionFunction.Registry',{noproc,{'Elixir.GenServer',call,['Elixir.Mix.ProjectStack',{get,#Fun<Elixir.Mix.ProjectStack.11.118167275>},30000]}}}},{'Elixir.SPARQL.Application',start,[normal,[]]}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,sparql,{{shutdown,{failed_to_start_child,'Elixir.SPARQL.ExtensionFunction.Registry',{noproc,{'Elixir.GenServer',call,['Elixir

Crash dump is being written to: erl_crash.dump...done
```

In the  erl_crash.dump I can find the following.

```
Tue Feb 26 17:43:58 2019
Slogan: Kernel pid terminated (application_controller) ({application_start_failure,sparql,{{shutdown,{failed_to_start_child,'Elixir.SPARQL.ExtensionFunction.Registry',{noproc,{'Elixir.GenServer',call,['Elixir
System version: Erlang/OTP 21 [erts-10.2.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]
```

I guess I just need to configure something correctly -> but I have no idea where to start looking.

Thank you very much for your help

**Comment by marcelotto** [comment]
First I must say I'm not very experienced with Distillery, so I would have to do some basic research myself. Any help from people more familiar with Distillery would be appreciated. But in general a little more information seems necessary:

- What versions of Elixir and Distillery are you using?
- Are you writing an umbrella application?
- As many contents of your mix file, your release configuration file, and your `application.ex` file (at least the process layout from your `Application.start/2` function) you're able the share.

**Comment by marcelotto** [comment]
Found the issue. Will release a fix soon. 

Kudos to @padde for the help.

**Comment by marcelotto** [comment]
Version 0.2.9 should fix the issue. Feel free reopen if that's not the case.
